version: "3.9"
services:
  api:
    image: test-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      SPRING_DATASOURCE_USERNAME: dytni
      SPRING_DATASOURCE_PASSWORD: 1331
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "products"
      POSTGRES_USER: "dytni"
      POSTGRES_PASSWORD: "1331"
    ports:
      - "5432:5432"

